# Generated by Django 3.0.2 on 2020-01-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsMenees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_menee', models.TextField(max_length=800, null=True)),
                ('action_representation_interet_id', models.IntegerField(null=True)),
                ('action_menee_autre', models.TextField(max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Affiliations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representants_id', models.IntegerField(null=True)),
                ('denomination_affiliation', models.TextField(blank=True, max_length=60, null=True)),
                ('identifiant_national_affiliation', models.TextField(blank=True, max_length=15, null=True)),
                ('type_identifiant_national_affiliation', models.TextField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaire_action_menee', models.TextField(blank=True, max_length=250, null=True)),
                ('action_representation_interet_id', models.IntegerField(null=True)),
                ('action_menee_en_propre', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representants_id', models.IntegerField(null=True)),
                ('denomination_client', models.TextField(blank=True, max_length=60, null=True)),
                ('identifiant_national_client', models.TextField(blank=True, max_length=15, null=True)),
                ('type_identifiant_national_client', models.TextField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborateurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite_collaborateur', models.TextField(blank=True, max_length=3, null=True)),
                ('fonction_collaborateur', models.TextField(blank=True, max_length=60, null=True)),
                ('nom_collaborateur', models.TextField(blank=True, max_length=30, null=True)),
                ('prenom_collaborateur', models.TextField(blank=True, max_length=30, null=True)),
                ('representants_id', models.IntegerField(null=True)),
                ('nom_prenom_collaborateur', models.TextField(blank=True, max_length=61, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DecisionsConcernees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_concernee', models.TextField(blank=True, max_length=300, null=True)),
                ('action_representation_interet_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DfDirigeants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representants_id', models.IntegerField(null=True)),
                ('dirigeant', models.TextField(blank=True, max_length=300, null=True)),
                ('fonction_dirigeant', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dirigeants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite_dirigeant', models.TextField(blank=True, max_length=3, null=True)),
                ('fonction_dirigeant', models.TextField(blank=True, max_length=60, null=True)),
                ('nom_dirigeant', models.TextField(blank=True, max_length=30, null=True)),
                ('prenom_dirigeant', models.TextField(blank=True, max_length=30, null=True)),
                ('representants_id', models.IntegerField(null=True)),
                ('nom_prenom_dirigeant', models.TextField(blank=True, max_length=61, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomainesInterventionsActionsMenees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaines_intervention_actions_menees', models.TextField(blank=True, max_length=600, null=True)),
                ('activite_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercices_id', models.IntegerField(null=True)),
                ('representants_id', models.IntegerField(null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('exercice_sans_activite', models.BooleanField(null=True)),
                ('nombre_activites', models.IntegerField(blank=True, null=True)),
                ('declaration_incomplete', models.BooleanField(null=True)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('exercice_sans_CA', models.BooleanField(null=True)),
                ('montant_depense', models.CharField(blank=True, max_length=12, null=True)),
                ('nombre_salaries', models.FloatField(blank=True, null=True)),
                ('chiffre_affaires', models.CharField(blank=True, max_length=12, null=True)),
                ('annee_debut', models.IntegerField(blank=True, null=True)),
                ('annee_fin', models.IntegerField(blank=True, null=True)),
                ('montant_depense_inf', models.IntegerField(blank=True, null=True)),
                ('montant_depense_sup', models.IntegerField(blank=True, null=True)),
                ('ca_inf', models.IntegerField(blank=True, null=True)),
                ('ca_sup', models.TextField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformationsGenerales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representants_id', models.IntegerField(null=True)),
                ('adresse', models.TextField(blank=True, max_length=250, null=True)),
                ('code_postal', models.TextField(max_length=20, null=True)),
                ('derniere_publication_activite', models.DateTimeField(null=True)),
                ('date_premiere_publication', models.DateTimeField(blank=True, null=True)),
                ('declaration_organisation_appartenance', models.BooleanField(null=True)),
                ('declaration_tiers', models.BooleanField(null=True)),
                ('denomination', models.TextField(blank=True, max_length=250, null=True)),
                ('identifiant_national', models.TextField(max_length=10)),
                ('activites_publiees', models.BooleanField(null=True)),
                ('page_facebook', models.TextField(blank=True, max_length=300, null=True)),
                ('page_linkedin', models.TextField(blank=True, max_length=300, null=True)),
                ('page_twitter', models.TextField(blank=True, max_length=300, null=True)),
                ('site_web', models.TextField(blank=True, max_length=200, null=True)),
                ('nom_usage_HATVP', models.TextField(blank=True, max_length=50, null=True)),
                ('pays', models.TextField(blank=True, max_length=50, null=True)),
                ('sigle_hatvp', models.TextField(blank=True, max_length=50, null=True)),
                ('type_identifiant_national', models.TextField(blank=True, max_length=15, null=True)),
                ('ville', models.TextField(blank=True, max_length=100, null=True)),
                ('label_categorie_organisation', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinisteresAaiApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_representation_interet_id', models.IntegerField(null=True)),
                ('responsable_public', models.TextField(blank=True, max_length=300, null=True)),
                ('departement_ministeriel', models.TextField(blank=True, max_length=300, null=True)),
                ('responsable_public_ou_dpt_ministeriel_autre', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NiveauxInterventions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_intervention', models.TextField(blank=True, max_length=250, null=True)),
                ('representants_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetsActivites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activite_id', models.IntegerField(null=True)),
                ('exercices_id', models.IntegerField(null=True)),
                ('date_publication_activite', models.DateField(blank=True, null=True)),
                ('identifiant_fiche', models.TextField(blank=True, max_length=8, null=True)),
                ('objet_activite', models.TextField(max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_representation_interet_id', models.IntegerField(null=True)),
                ('activite_id', models.IntegerField(null=True)),
                ('observation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecteursActivites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secteur_activite', models.TextField(blank=True, max_length=100, null=True)),
                ('representants_id', models.IntegerField(null=True)),
            ],
        ),
    ]
