# Generated by Django 3.0.2 on 2020-01-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp_app', '0002_dftwofive'),
    ]

    operations = [
        migrations.CreateModel(
            name='DfOneOneEight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representants_id', models.IntegerField(null=True)),
                ('denomination', models.TextField(blank=True, max_length=300, null=True)),
                ('label_categorie_organisation', models.TextField(blank=True, max_length=300, null=True)),
                ('dirigeant', models.TextField(blank=True, max_length=300, null=True)),
                ('fonction_dirigeant', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
